### ISSUE TITLE
Side positionals are 90°, are they not?

### ISSUE THREAD

**Issue by Iaotle** [aulus-asina/resonant#1]
The plugin gives 45° of side positional area. Shouldn't these be 90°? I understand that you're not really supposed to be in that area 99% of the time as melee, but still it should be an option IMO.

**Comment by aulus-asina** [comment]
Sweet Zenos, I might have had this misconception for a while. I'll test this in a bit and get an update out if it holds true.

**Comment by aulus-asina** [comment]
Tested and confirmed, with a fix in https://github.com/aulus-asina/resonant/commit/9f0938868df2ac10425ba29eb4b305a41fc7cd71 . Give it a go and let me know what you think.

**Comment by Iaotle** [comment]
Don't worry it was a surprise to me too ;)

**Comment by Iaotle** [comment]
0.0.0.3 is broken btw

**Comment by aulus-asina** [comment]
That is peculiar, might have been an artifact of reusing `latest` as a tag. I've deleted the release and rebuilt it, which seems to be working for me now. I'll have to improve on that release process later.
