### ISSUE TITLE
I'm currently maintaining this plugin on my repository

### ISSUE THREAD

**Issue by k-kz** [aulus-asina/resonant#17]
I'm going to be keeping Resonant up to date on my repo for the foreseeable future, until/if @aulus-asina decides to come back and pick it back up. Just leaving this here for anyone still wanting to use it and isn't able to maintain it for themselves.

https://github.com/k-kz/Resonant-API8

**Comment by Theletha** [comment]
> I'm going to be keeping Resonant up to date on my repo for the foreseeable future, until/if @aulus-asina decides to come back and pick it back up. Just leaving this here for anyone still wanting to use it and isn't able to maintain it for themselves.
> 
> https://github.com/k-kz/Resonant-API8

will you update for api9?
