### ISSUE TITLE
Only draw positionals when on melee DPS.

### ISSUE THREAD

**Issue by Iaotle** [aulus-asina/resonant#2]
Only draw positionals when on melee DPS, since there is no need for them otherwise.

**Comment by aulus-asina** [comment]
I am working on profile based functionality with job based auto-switching, which should handle this case.

**Comment by aulus-asina** [comment]
Implemented in https://github.com/aulus-asina/resonant/commit/32399b31c561569ec0da4192b7d066ff06ebf2fe and released in version `0.0.0.4`. Give it a shot and let me know what you think.
